name: Compile and Run imagine.h tests
on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [windows-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile imagine tests
        run: ${{ matrix.cc }} -O2 -std=c89 -pedantic -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wsign-conversion -Wuninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs -o imagine_test_${{ matrix.cc }}.exe tests/imagine_test.c
      - name: Run imagine tests
        run: .\imagine_test_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.cc }}-imagine_test
          path: imagine_test_${{ matrix.cc }}.exe
